#!/usr/bin/env python3.6
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Sun May  3 21:55:06 2020
#

from PIL import Image, ImageDraw, ImageFont
import wx, os, shutil, glob, wx.adv, time

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

class My_Ventana(wx.Frame):
	def __init__(self, *args, **kwds):
		# begin wxGlade: My_Ventana.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
		wx.Frame.__init__(self, *args, **kwds)
		self.SetSize((450, 550))
		self.muestra_valor = wx.StaticText(self, wx.ID_ANY, "100%")
		self.slider_1 = wx.Slider(self, wx.ID_ANY, 100, 1, 100)
		self.etiqueta_ruta_in = wx.StaticText(self, wx.ID_ANY, "Carpeta Origen...")
		self.button_1 = wx.Button(self, wx.ID_ANY, "Selecciona carpeta")
		self.etiqueta_ruta_out = wx.StaticText(self, wx.ID_ANY, "Carpeta Destino...")
		self.button_3 = wx.Button(self, wx.ID_ANY, "Selecciona carpeta")
		self.button_2 = wx.Button(self, wx.ID_ANY, "INICIAR")

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_COMMAND_SCROLL, self.OnScroll, self.slider_1)
		self.Bind(wx.EVT_COMMAND_SCROLL_CHANGED, self.OnScroll, self.slider_1)
		self.Bind(wx.EVT_BUTTON, self.OnClick, self.button_1)
		self.Bind(wx.EVT_BUTTON, self.OnClick3, self.button_3)
		self.Bind(wx.EVT_BUTTON, self.OnClick2, self.button_2)
		# end wxGlade

		self.Bind(wx.EVT_MENU, self.Cerrar, id=104)
		self.Bind(wx.EVT_MENU, self.Acerca, id=105)
		self.Bind(wx.EVT_MENU, self.INSTRUCCIONES, id=107)

		# Barra de menú
		self.frame_menubar = wx.MenuBar()
		''' MENU ARCHIVO '''
		self.Archivo = wx.Menu()
		self.Archivo.Append(105, "&Acerca de RIS")
		self.Archivo.Append(104, '&Cerrar', "Cierra esta ventana")
		self.frame_menubar.Append(self.Archivo, "Archivo")
		''' MENU INSTRUCCIONES '''
		self.instrucciones = wx.Menu()
		self.instrucciones.Append(107, "&Instrucciones de RIS", "Instrucciones de este software")
		self.frame_menubar.Append(self.instrucciones, "Instrucciones")
		self.SetMenuBar(self.frame_menubar)
		# Fín barra de menú

	def __set_properties(self):
		# begin wxGlade: My_Ventana.__set_properties
		self.SetTitle("Optimizador de Imagenes")
		self.SetBackgroundColour(wx.Colour(255, 253, 212))
		self.SetForegroundColour(wx.Colour(50, 50, 204))
		self.muestra_valor.SetMinSize((70, 25))
		self.muestra_valor.SetFont(wx.Font(18, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
		self.slider_1.SetMinSize((300, 60))
		self.button_2.SetMinSize((200, 30))
		self.button_2.SetBackgroundColour(wx.Colour(50, 50, 204))
		self.button_2.SetForegroundColour(wx.Colour(249, 255, 252))
		self.button_2.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: My_Ventana.__do_layout
		grid_sizer_1 = wx.GridSizer(10, 1, 0, 0)
		label_1 = wx.StaticText(self, wx.ID_ANY, u"Reductor de imágenes Sencillo - RIS")
		label_1.SetMinSize((380, 23))
		label_1.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, ""))
		grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.TOP, 12)
		grid_sizer_1.Add(self.muestra_valor, 1, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 30)
		grid_sizer_1.Add(self.slider_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 17)
		label_2 = wx.StaticText(self, wx.ID_ANY, u"NIVEL DE CALIDAD")
		grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		grid_sizer_1.Add(self.etiqueta_ruta_in, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 17)
		grid_sizer_1.Add(self.button_1, 0, wx.ALIGN_CENTER, 0)
		grid_sizer_1.Add(self.etiqueta_ruta_out, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 17)
		grid_sizer_1.Add(self.button_3, 0, wx.ALIGN_CENTER, 0)
		grid_sizer_1.Add(self.button_2, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
		label_3 = wx.StaticText(self, wx.ID_ANY, "GPLv3")
		grid_sizer_1.Add(label_3, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.RIGHT, 17)
		self.SetSizer(grid_sizer_1)
		self.Layout()
		self.Centre()
		# end wxGlade

#DIALOGO PARA SELECCIONAR RUTA DE FOTOS
	def OnClick(self, event):  # wxGlade: My_Ventana.<event_handler>
		dialog_in = wx.DirDialog(None, "Ubicacion actual de tus imagenes:",style=wx.DD_DEFAULT_STYLE | wx.DD_NEW_DIR_BUTTON)
		if dialog_in.ShowModal() == wx.ID_OK:
			self.ruta_in = dialog_in.GetPath()
			self.etiqueta_ruta_in.SetLabelText(self.ruta_in)
		dialog_in.Destroy()
		event.Skip()

#DIALOGO PARA SELECCIONAR DIRECTORIO DESTINO DE LAS FOTOS
	def OnClick3(self, event):  # wxGlade: My_Ventana.<event_handler>
		dialog_out = wx.DirDialog(None, "Destino de las imagenes optimizadas:",style=wx.DD_DEFAULT_STYLE | wx.DD_NEW_DIR_BUTTON)
		if dialog_out.ShowModal() == wx.ID_OK:
			self.ruta_out = dialog_out.GetPath()
			self.etiqueta_ruta_out.SetLabelText(self.ruta_out)
		event.Skip()

	def OnScroll(self, event):  # wxGlade: My_Ventana.<event_handler>
		self.valor_seleccionado = self.slider_1.GetValue()
		self.muestra_valor.SetLabelText(str(self.valor_seleccionado)+'%')
		event.Skip()

	def Acerca(self, event):  # wxGlade: My_Ventana.<event_handler>
		info = wx.adv.AboutDialogInfo()
		minitutorial = '''
		MINITUTORIAL

		1- Desplaza el slider hasta el nivel de calidad que aceptas reducir.
		2- Primer Botón: Selecciona carpeta origen de tus imágenes.
		3- Segundo Botón: Selecciona la carpeta destino y dale en INICIAR

		NOTA: Un alto valor de calidad (menos del 30%) puede producir perdidas importantes en la calidad de las imágenes. Haga pruebas.
		'''

		licencia = '''
		Copyright 2020 Erwin Andres Espitia Torres
		Este programa es software libre: puede redistribuirlo y / o modificarlo
		bajo los términos de la Licencia Pública General GNU publicada por
		Free Software Foundation, ya sea la versión 3 de la Licencia, o
		(a su elección) cualquier versión posterior.

		Este programa se distribuye con la esperanza de que sea útil,
		pero SIN NINGUNA GARANTÍA; sin siquiera la garantía implícita de
		COMERCIABILIDAD o APTITUD PARA UN PROPÓSITO EN PARTICULAR. Ver el
		Licencia pública general de GNU para más detalles.

		Debería haber recibido una copia de la Licencia Pública General de GNU
		junto con este programa. Si no, vea <http://www.gnu.org/licenses/>.

		Licencia GPLv3

		'''
		info.SetName('RIS - Reductor de Imágenes Sencillo')
		info.SetVersion('1.0')
		info.SetDescription(minitutorial)
		info.SetCopyright('(C) 2020 Erwin Andrés Espitia Torres')
		info.SetWebSite('https://www.espaciotecnologico.co')
		info.SetLicence(licencia)
		info.AddDeveloper('Erwin Andrés Espitia Torres')
		info.AddDocWriter('Erwin Andrés Espitia Torres')
		wx.adv.AboutBox(info)
		#wx.MessageBox('RIS - Reductor de Imágenes Sencillo --- La función de este programa es para reducir el peso de los archivos de imágenes y fotos', 'Acerca de RIS', wx.OK | wx.ICON_INFORMATION)
		event.Skip()

	def INSTRUCCIONES(self, event):
		wx.MessageBox("1- Desplaza el slider hasta el nivel de calidad que aceptas reducir.   2- Primer Botón: Selecciona carpeta origen de tus imágenes    3- Segundo Botón: Selecciona carpeta destino y dale en INICIAR", "Minitutorial", wx.OK | wx.ICON_INFORMATION)

	def Cerrar(self, event):  # wxGlade: My_Ventana.<event_handler>
		exit()
		event.Skip()

	def OnClick2(self, event):  # wxGlade: My_Ventana.<event_handler>
		#self.button_2.SetBackgroundColour(wx.Colour(0,255,0))
		self.button_2.SetLabelText("PROCESANDO")
		self.button_2.SetBackgroundColour(wx.Colour(84, 231, 79))
		wx.MessageBox("Va a comenzar el proceso. Pulsa en Aceptar para continuar", "Información", wx.OK | wx.ICON_INFORMATION)
#CALCULAMOS EL NUMERO DE ARCHIVOS QUE CONTIENE EL DIRECTORIO ORIGEN PARA ALIMENTAR LA BARRA DE PROGRESO
		directorio_origen = self.ruta_in
		lista = os.listdir(directorio_origen)
		self.topeMaximo = len(lista)
		self.cuenta = 0
#INVOCAMOS LA BARRA DE PROGRESO DEL PROCESO DE REDUCCIÓN DE IMÁGENES
		self.dialog = wx.ProgressDialog("Progreso del proceso", "Tiempo transcurrido", self.topeMaximo, style=wx.PD_CAN_ABORT | wx.PD_ELAPSED_TIME | wx.PD_REMAINING_TIME)
#ACTIVAMOS LA FUNCIÓN QUE REALIZA EL PROCESO DE REDUCCIÓN DE IMAGENES
		self.gatillo()
		self.dialog.Destroy()
		event.Skip()

#INICIA EL PROCESO DE OPTIMIZACION

	def gatillo(self):
	#FUNCION PARA OBTENER LA LISTA DE IMAGENES SEGUN EL DIRECTORIO SELECCIONADO
		def getListOfFiles(dirName):

			lista_de_archivos = os.listdir(dirName)
			allFiles = list()
# Iterar sobre todo lo que le entre desde la variable 'lista_de_archivos'
			for entry in lista_de_archivos:
# Creamos la ruta completa del directorio que contiene los archivos de imágenes
				fullPath = os.path.join(dirName, entry)
# Si la entrada es un directorio, entonces tomamos la ruta completa de los archivos
				if os.path.isdir(fullPath):
					allFiles = allFiles + getListOfFiles(fullPath)
				else:
					allFiles.append(fullPath)

			return allFiles

		dirName = self.ruta_in
		dirName_out = self.ruta_out

#OPTIMIZA LA IMAGEN
		image_font_path = dirName
		image_path_input = dirName
		image_path_output = dirName

# LLAMAMOS LA FUNCION getListOfFiles PARA PASARLA POR UN CICLO FOR
# EL CICLO FOR ENTREGA CADA IMAGEN ENCONTRADA AL FRAGMENTO QUE OPTIMIZA LAS IMAGENES
		lista_de_archivos = getListOfFiles(dirName)

		archivo_texto=dirName_out+"/resultado.txt"
		f= open(archivo_texto,"w")

# Volemos a iterar sobre la lista de archivos para filtar solo los archivos JPG
		for elem in lista_de_archivos:

			if elem.endswith(".jpg"):

				image_name_input = elem
#FRAGMENTO QUE OPTIMIZA LA IMAGENES. EN ESTE PUNTO COMIENZA LA REDUCCIÓN DEL PESO DE LAS IMÁGENES
				im = Image.open(image_name_input)
				print('NOMBRE DE LA IMAGEN ORIGINAL   : ', image_name_input, file = f)
				print('RESOLUCIÓN  : ', im.size)
				print('TAMAÑO ORIGINAL : ', round((os.path.getsize (image_name_input)/1000), 2), file = f)

		# image_name_output = '05_compress_image_01_output.png'
				image_name_output = elem+time.strftime("%d-%m-%y_%H:%M:%S")+'RIS_ok_.jpg'

				#TOMAMOS EL VALOR DE REDUCCION QUE DEFINE EL USUARIO POR MEDIO DEL SLIDER
				valor_reduccion = self.slider_1.GetValue()

				im.save(image_name_output ,optimize=True,quality=valor_reduccion)

				print(" ", file = f)
				print('NUEVO TAMAÑO : ', round((os.path.getsize (image_name_output)/1000), 2), file = f)
				print('PORCENTAJE DE REDUCCIÓN: ', valor_reduccion, file = f)
				print("->-->-->-->-->-->-->-->-->-->-->", file = f)

				extension = '/*ok*'
				nombre_completo = dirName+extension

				for archivo2 in glob.glob(nombre_completo):
					shutil.move(archivo2, dirName_out)

				self.cuenta += 1
				self.dialog.Update(self.cuenta)

# MOVEMOS LAS IMAGENES OPTIMIZADAS AL DIRECTORIO DE DESTINO SELECCIONADO

		f.close()
		self.button_2.SetBackgroundColour(wx.Colour(50, 50, 204))
		self.button_2.SetLabelText("INICIAR")

		wx.MessageBox("Proceso finalizado. Revisa el archivo resultado.txt en la carpeta destino", "Información", wx.OK | wx.ICON_INFORMATION)

# end of class My_Ventana

class MyApp(wx.App):
	def OnInit(self):
		self.frame = My_Ventana(None, wx.ID_ANY, "")
		self.SetTopWindow(self.frame)
		self.frame.Show()
		return True

# end of class MyApp

if __name__ == "__main__":
	app = MyApp(0)
	app.MainLoop()
